=== noegeo01/curso20212022/LMGI/T5-XML/ActT5_02/esquema_persona.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="personas">
        
    </xs:element>
    <xs:element name="persona">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:maxLength value="30"></xs:maxLength>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="apellidos">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:maxLength value="40"></xs:maxLength>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="direccion">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:maxLength value="20"></xs:maxLength>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="dni">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:length value="9"></xs:length>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="telefono">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:length value="10"></xs:length>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="cod_postal">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:length value="5"></xs:length>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="ciudad">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:maxLength value="15"></xs:maxLength>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="provincia">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:maxLength value="15"></xs:maxLength>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== noegeo01/curso20212022/LMGI/T5-XML/ActT5_02/persona.xml
<?xml version="1.0" encoding="UTF-8"?>
<personas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="esquema_persona.xsd">
    <persona>
        <nombre>Maria</nombre>
        <apellidos>Ocampo</apellidos>
        <direccion>c/ hospital</direccion>
        <dni>45646612j</dni>
        <telefono>6155556069</telefono>
        <cod_postal>30510</cod_postal>
        <ciudad>Yecla</ciudad>
        <provincia>Murcia</provincia>
    </persona>
    <persona>
        <nombre>Juan</nombre>
        <apellidos>Martinez</apellidos>
        <direccion>c/ alferez maestre</direccion>
        <dni>45635465x</dni>
        <telefono>6551274895</telefono>
        <cod_postal>30510</cod_postal>
        <ciudad>Yecla</ciudad>
        <provincia>Murcia</provincia>
    </persona>
    <persona>
        <nombre>Jefferson</nombre>
        <apellidos>Vasquez </apellidos>
        <direccion>c/cruz de piedra </direccion>
        <dni>44355212r</dni>
        <telefono>6521351328</telefono>
        <cod_postal>30510</cod_postal>
        <ciudad>Yecla</ciudad>
        <provincia>Murcia</provincia>
    </persona>
</personas>
