=== noegeo01/curso20212022/LMGI/T5-XML/ActT5_02/esquema_filmoteca.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="filmoteca">

    </xs:element>
    <xs:element name="pelicula">

        <xs:complexType>
            <xs:sequence>
                <xs:element name="titulo" minOccurs="1" maxOccurs="3"> 
                    <xs:complexType>
                         <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="idioma" default="es" ></xs:attribute>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>                    
                </xs:element>
                <xs:element name="director" type="xs:string"></xs:element>
                <xs:element name="anyo" type="xs:string"></xs:element>
                <xs:element name="nacionalidad" type="xs:string"></xs:element>
            </xs:sequence>
            <xs:attribute name="codigo" type="xs:string"/>      
        </xs:complexType>
    
    </xs:element>
</xs:schema>

=== noegeo01/curso20212022/LMGI/T5-XML/ActT5_02/filmoteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<filmoteca xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="esquema_filmoteca.xsd">
  <pelicula codigo='p0001'>
    <titulo idioma="es">Cinema Paradiso</titulo>
    <director>Giuseppe Tornatore</director>
    <anyo>1988</anyo>
    <nacionalidad>Italia</nacionalidad>
  </pelicula>
  <pelicula codigo='p0002'>
    <titulo idioma="es">Forrest Gump</titulo>
    <director>Robert Zemeckis</director>
    <anyo>1994</anyo>
    <nacionalidad>EEUU</nacionalidad>
  </pelicula>
  <pelicula codigo='p0003'>
    <titulo idioma="es">Días de fútbol</titulo>
    <titulo idioma="en">Soccer days</titulo>
    <director>David Serrano</director>
    <anyo>2003</anyo>
    <nacionalidad>España</nacionalidad>
  </pelicula>
</filmoteca>
