=== noegeo01/curso20212022/LMGI/T5-XML/estructuraBiblioteca.dtd
<!ELEMENT biblioteca (libro*)>
<!ELEMENT libro (titulo,autor,fechaPublicacion)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ATTLIST autor fechanacimiento CDATA #IMPLIED>
<!ELEMENT fechaPublicacion (#PCDATA)>
<!ATTLIST fechaPublicacion aÃ±o CDATA #REQUIRED>

=== noegeo01/curso20212022/LMGI/T5-XML/ejemplo.xml
<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "estructuraBiblioteca.dtd">
<biblioteca>
    <libro>
        <titulo>La vida esta enotra parte</titulo>
        <autor>Milan  Kundera</autor>
        <fechaPublicacion año="1973"/>
    </libro>
    <libro>
        <titulo>Pantaleon</titulo>
        <autor fechanacimiento="28/03/1936">Mario Vargas Llosa</autor>
        <fechaPublicacion año="1973"></fechaPublicacion>
    </libro>
    <libro>
        <titulo>Conversacion en la catedral</titulo>
        <autor fechanacimiento="28/03/1936">Mario Vargas Llosa</autor>
        <fechaPublicacion año="1969"></fechaPublicacion>
    </libro>
</biblioteca>
